import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../.env') });

import connectDB from '../src/db/config.js';
import Registration from '../src/models/registration.model.js';
import TournamentGroup from '../src/models/group.model.js';
import Fixture from '../src/models/fixture.model.js';
import Event from '../src/models/event.model.js';
import MatchSession from '../src/models/matchSession.model.js';
import Score from '../src/models/score.model.js';

async function cleanFakeData() {
  await connectDB();
  console.log('=== STARTING SAFE FAKE DATA CLEANUP ===\n');

  // 1. Identify fake registration query
  const fakeRegQuery = {
    $or: [
      { captainEmail: { $regex: /(@example\.com|@test\.com|@live\.com|testuser_)/i } },
      { teamName: { $regex: /^(PT Team|Apex Strikers|Vortex Warriors|Live Team|E2E Titans|E2E Warriors|Warriors XI|Phoenix Strikers|Titan Warriors|Test Team)/i } },
    ],
  };

  const fakeRegistrations = await Registration.find(fakeRegQuery);
  const fakeTeamNames = new Set(fakeRegistrations.map(r => r.teamName.trim().toLowerCase()));
  fakeTeamNames.add('mumbai titans');
  fakeTeamNames.add('phoenix strikers');
  fakeTeamNames.add('titan warriors');

  console.log(`Found ${fakeRegistrations.length} fake demo registration(s) to remove:`);
  fakeRegistrations.forEach(r => console.log(` - ${r.teamName} (${r.captainEmail})`));

  // Delete fake registrations
  const delRegResult = await Registration.deleteMany(fakeRegQuery);
  console.log(`✓ Deleted ${delRegResult.deletedCount} fake registration(s).`);

  // 2. Delete test events (only test events generated by test scripts)
  const fakeEvents = await Event.find({
    title: { $regex: /^(Test Tournament|PT Tournament)/i },
  });
  const fakeEventIds = fakeEvents.map(e => e._id);
  if (fakeEventIds.length > 0) {
    await Event.deleteMany({ _id: { $in: fakeEventIds } });
    console.log(`✓ Deleted ${fakeEventIds.length} test event(s).`);
  }

  // 3. Clean up fake teams from Tournament Groups
  const groups = await TournamentGroup.find({});
  for (const g of groups) {
    // If group belongs to a deleted fake test event/tournament, delete it
    if (fakeEventIds.map(id => id.toString()).includes(g.tournamentId) || g.tournamentId.startsWith('test-')) {
      await TournamentGroup.findByIdAndDelete(g._id);
      console.log(`✓ Deleted fake tournament group: ${g.groupName} (${g.tournamentId})`);
      continue;
    }

    const filteredTeams = (g.teams || []).filter(t => !fakeTeamNames.has(t.trim().toLowerCase()));
    if (filteredTeams.length !== (g.teams || []).length) {
      g.teams = filteredTeams;
      await g.save();
      console.log(`✓ Cleaned fake teams from group ${g.groupName} (${g.tournamentId}). New roster: [${g.teams.join(', ')}]`);
    }
  }

  // 4. Clean up fake fixtures
  const fakeFixtures = await Fixture.find({
    $or: [
      { team1: { $in: Array.from(fakeTeamNames).map(t => new RegExp(`^${t}$`, 'i')) } },
      { team2: { $in: Array.from(fakeTeamNames).map(t => new RegExp(`^${t}$`, 'i')) } },
      { tournamentId: { $in: ['test-tournament-2025', ...fakeEventIds.map(id => id.toString())] } },
    ],
  });

  const fakeMatchIds = fakeFixtures.map(f => f.matchId).filter(Boolean);
  const delFixResult = await Fixture.deleteMany({
    _id: { $in: fakeFixtures.map(f => f._id) },
  });
  console.log(`✓ Deleted ${delFixResult.deletedCount} fake fixture(s).`);

  // 5. Clean up fake match sessions & scores
  // Also include any matchSessions with fake teams
  const fakeSessions = await MatchSession.find({
    $or: [
      { matchId: { $in: fakeMatchIds } },
      { 'team1Squad.teamName': { $in: Array.from(fakeTeamNames).map(t => new RegExp(`^${t}$`, 'i')) } },
      { 'team2Squad.teamName': { $in: Array.from(fakeTeamNames).map(t => new RegExp(`^${t}$`, 'i')) } },
    ],
  });
  const allFakeMatchIds = Array.from(new Set([...fakeMatchIds, ...fakeSessions.map(s => s.matchId)]));

  if (allFakeMatchIds.length > 0) {
    const delSessResult = await MatchSession.deleteMany({ matchId: { $in: allFakeMatchIds } });
    console.log(`✓ Deleted ${delSessResult.deletedCount} fake match session(s).`);

    const delScoreResult = await Score.deleteMany({ matchId: { $in: allFakeMatchIds } });
    console.log(`✓ Deleted ${delScoreResult.deletedCount} fake score record(s).`);
  }

  // 6. Verification
  console.log('\n=== VERIFICATION AFTER CLEANUP ===');
  const remainingRegs = await Registration.find({}).select('teamName captainName captainEmail registrationStatus eventId');
  console.log(`Remaining Genuine Registrations (${remainingRegs.length}):`);
  remainingRegs.forEach(r => console.log(` - ${r.teamName} (Capt: ${r.captainName}, Email: ${r.captainEmail}, Status: ${r.registrationStatus}, EventId: ${r.eventId})`));

  const remainingGroups = await TournamentGroup.find({});
  console.log(`Remaining Groups (${remainingGroups.length}):`);
  remainingGroups.forEach(g => console.log(` - ${g.tournamentId} / ${g.groupName}: [${g.teams.join(', ')}]`));

  const remainingFixtures = await Fixture.find({});
  console.log(`Remaining Fixtures (${remainingFixtures.length}):`);
  remainingFixtures.forEach(f => console.log(` - ${f.team1} vs ${f.team2} (${f.status}) [${f.matchId}]`));

  const remainingSessions = await MatchSession.find({});
  console.log(`Remaining Match Sessions (${remainingSessions.length}):`);
  remainingSessions.forEach(s => console.log(` - ${s.matchId}: ${s.team1Squad?.teamName} vs ${s.team2Squad?.teamName} (${s.status})`));

  await mongoose.disconnect();
  console.log('\n✅ Cleanup and verification complete!');
}

cleanFakeData();
